# Exercise 6-2: Clean the Cars data

## Read the data

In [3]:
import pandas as pd

In [4]:
cars = pd.read_csv('cars.csv')

In [5]:
# display the first 5 rows
cars.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

## Examine the data

In [7]:
# info()
cars.info(verbose=True, memory_usage='deep', show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 149.9 KB

In [8]:
# value_counts()
cars.fueltype.value_counts().head()

fueltype
gas       185
diesel     20
Name: count, dtype: int64

In [9]:
# unique()
cars.apply(pd.unique)

car_ID              [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
symboling                                        [3, 1, 2, 0, -1, -2]
CarName             [alfa-romero giulia, alfa-romero stelvio, alfa...
fueltype                                                [gas, diesel]
aspiration                                               [std, turbo]
doornumber                                                [two, four]
carbody               [convertible, hatchback, sedan, wagon, hardtop]
drivewheel                                            [rwd, fwd, 4wd]
enginelocation                                          [front, rear]
wheelbase           [88.6, 94.5, 99.8, 99.4, 105.8, 99.5, 101.2, 1...
carlength           [168.8, 171.2, 176.6, 177.3, 192.7, 178.2, 176...
carwidth            [64.1, 65.5, 66.2, 66.4, 66.3, 71.4, 67.9, 64....
carheight           [48.8, 52.4, 54.3, 53.1, 55.7, 55.9, 52.0, 53....
curbweight          [2548, 2823, 2337, 2824, 2507, 2844, 2954, 308...
enginetype                   [dohc, ohcv, ohc, l, rotor, ohcf, dohcv]
cylindernumber           [four, six, five, three, twelve, two, eight]
enginesize          [130, 152, 109, 136, 131, 108, 164, 209, 61, 9...
fuelsystem             [mpfi, 2bbl, mfi, 1bbl, spfi, 4bbl, idi, spdi]
boreratio           [3.47, 2.68, 3.19, 3.13, 3.5, 3.31, 3.62, 2.91...
stroke              [2.68, 3.47, 3.4, 2.8, 3.19, 3.39, 3.03, 3.11,...
compressionratio    [9.0, 10.0, 8.0, 8.5, 8.3, 7.0, 8.8, 9.5, 9.6,...
horsepower          [111, 154, 102, 115, 110, 140, 160, 101, 121, ...
peakrpm             [5000, 5500, 5800, 4250, 5400, 5100, 4800, 600...
citympg             [21, 19, 24, 18, 17, 16, 23, 20, 15, 47, 38, 3...
highwaympg          [27, 26, 30, 22, 25, 20, 29, 28, 53, 43, 41, 3...
price               [13495.0, 16500.0, 13950.0, 17450.0, 15250.0, ...
dtype: object

## Fix spelling and capitalization problems in the data

In [11]:
cars['brand'] = cars.apply(lambda x: x.CarName.split(' ')[0], axis=1)
cars['name'] = cars.apply(lambda x: ' '.join(x.CarName.split(' ')[1:]), axis=1)

In [12]:
# display each unique value in the brand column
cars.brand.unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'maxda', 'mazda', 'buick', 'mercury',
       'mitsubishi', 'Nissan', 'nissan', 'peugeot', 'plymouth', 'porsche',
       'porcshce', 'renault', 'saab', 'subaru', 'toyota', 'toyouta',
       'vokswagen', 'volkswagen', 'vw', 'volvo'], dtype=object)

In [13]:
# fix any misspellings or inconsistent capitalization in the brand names
cars.brand.replace(to_replace=['maxda', 'Nissan', 'porchshce', 'toyouta', 'vokswagen', 'volkswagen'], value=['mazda', 'nissan', 'porsche', 'toyota', 'vw', 'vw'] , inplace=True)

In [14]:
# store the fixed data in the CarName column
cars['CarName'] = cars['brand'] + ' ' + cars['name']

In [15]:
cars.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,brand,name
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero,giulia
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,16500.0,alfa-romero,stelvio
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,2.68,3.47,9.0,154,5000,19,26,16500.0,alfa-romero,Quadrifoglio
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,3.19,3.40,10.0,102,5500,24,30,13950.0,audi,100 ls
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,3.19,3.40,8.0,115,5500,18,22,17450.0,audi,100ls

## Rename and drop columns

In [17]:
# rename the CarName and the car_ID columns to brandname and carid
cars = cars.rename(columns={'CarName':'brandname', 'car_ID':'carid'})

In [18]:
cars.head()

,carid,symboling,brandname,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,brand,name
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero,giulia
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,16500.0,alfa-romero,stelvio
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,2.68,3.47,9.0,154,5000,19,26,16500.0,alfa-romero,Quadrifoglio
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,3.19,3.40,10.0,102,5500,24,30,13950.0,audi,100 ls
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,3.19,3.40,8.0,115,5500,18,22,17450.0,audi,100ls

In [19]:
# drop the carid and symbol columns
cars = cars.drop(columns=['carid', 'symboling'])

In [20]:
cars.head()

,brandname,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,brand,name
0,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero,giulia
1,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,3.47,2.68,9.0,111,5000,21,27,16500.0,alfa-romero,stelvio
2,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,2.68,3.47,9.0,154,5000,19,26,16500.0,alfa-romero,Quadrifoglio
3,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,3.19,3.40,10.0,102,5500,24,30,13950.0,audi,100 ls
4,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,3.19,3.40,8.0,115,5500,18,22,17450.0,audi,100ls